import { NumberInput } from './NumberInput'
import { type FormEvent, useEffect, useState } from 'react'
import type { AppState, Area, FocusCategory, Habit, UserSettings } from '../lib/domain'
import { AccessibleModal } from './AccessibleModal'

type CustomizeTab = 'profile' | 'focus' | 'habits' | 'reminders'
const areas: Area[] = ['Eğitim', 'Kariyer', 'İngilizce', 'Sağlık', 'Bilgi']

export function CustomizeModal({ state, hasActiveFocus, onClose, onOpenData, onSaveSettings, onSaveHabit, onArchiveHabit, onDeleteHabit, onAddFocusCategory, onSaveFocusCategory, onArchiveFocusCategory, onDeleteFocusCategory }: { state: AppState; hasActiveFocus: boolean; onClose: () => void; onOpenData: () => void; onSaveSettings: (settings: UserSettings) => Promise<boolean>; onSaveHabit: (habit: Habit) => Promise<boolean>; onArchiveHabit: (id: string, archived: boolean) => Promise<boolean>; onDeleteHabit: (id: string) => Promise<string>; onAddFocusCategory: (category: Omit<FocusCategory, 'id'>) => Promise<boolean>; onSaveFocusCategory: (category: FocusCategory) => Promise<boolean>; onArchiveFocusCategory: (id: string, archived: boolean) => Promise<boolean>; onDeleteFocusCategory: (id: string) => Promise<boolean> }) {
  const [tab, setTab] = useState<CustomizeTab>('profile')
  const [settingsDraft, setSettingsDraft] = useState(state.settings)
  const [status, setStatus] = useState('')
  const [focusMinutes, setFocusMinutes] = useState(String(state.settings.dailyFocusMinutes))
  const saveProfile = async (event: FormEvent) => {
    event.preventDefault()
    const minutes = Number(focusMinutes)
    if (!settingsDraft.name.trim()) { setStatus('İsim boş bırakılamaz.'); return }
    if (!Number.isFinite(minutes) || minutes < 15 || minutes > 1440) { setStatus('Günlük focus hedefi 15–1440 dakika arasında olmalı.'); return }
    const next = { ...settingsDraft, name: settingsDraft.name.trim(), dailyFocusMinutes: Math.round(minutes) }
    setSettingsDraft(next); setFocusMinutes(String(next.dailyFocusMinutes)); setStatus(await onSaveSettings(next) ? 'Profil ayarları kaydedildi.' : 'Kaydedilemedi. Girdiğin değerler korunuyor.')
  }
  const saveReminders = async (event: FormEvent) => {
    event.preventDefault()
    if (settingsDraft.reminders.enabled && (!('Notification' in window) || Notification.permission !== 'granted')) { setStatus('Önce bildirim izni vermelisin.'); return }
    setStatus(await onSaveSettings(settingsDraft) ? 'Hatırlatıcı saatleri kaydedildi.' : 'Kaydedilemedi. Girdiğin değerler korunuyor.')
  }
  const requestNotificationPermission = async () => {
    if (!('Notification' in window)) { setStatus('Bu tarayıcı bildirimleri desteklemiyor.'); return }
    const permission = await Notification.requestPermission()
    if (permission !== 'granted') { setStatus(permission === 'denied' ? 'Bildirim izni reddedildi. Tarayıcı/site ayarlarından açabilirsin.' : 'Bildirim izni verilmedi.'); return }
    const next = { ...settingsDraft, reminders: { ...settingsDraft.reminders, enabled: true } }
    setSettingsDraft(next); setStatus(await onSaveSettings(next) ? 'Bildirimler açıldı. Saatleri aşağıdan düzenleyebilirsin.' : 'Kaydedilemedi. Tekrar dene.')
  }
  const tabs: Array<{ id: CustomizeTab; label: string }> = [{ id: 'profile', label: 'Profil' }, { id: 'focus', label: 'Focus' }, { id: 'habits', label: 'Alışkanlıklar' }, { id: 'reminders', label: 'Hatırlatıcılar' }]
  return <AccessibleModal label="Momentum ayarları" className="card customize-modal" onClose={onClose}><div className="card-heading"><div><p className="eyebrow">KİŞİSEL MOMENTUM</p><h2>Ayarlar ve yönetim</h2></div><button type="button" className="modal-close" onClick={onClose} aria-label="Kapat">×</button></div>
    <div className="settings-tabs" role="tablist">{tabs.map((item) => <button type="button" role="tab" aria-selected={tab === item.id} className={tab === item.id ? 'active' : ''} key={item.id} onClick={() => { setTab(item.id); setStatus('') }}>{item.label}</button>)}</div>
    {tab === 'profile' && <form className="settings-form" onSubmit={saveProfile}><label>Adın<input autoFocus value={settingsDraft.name} maxLength={60} onChange={(event) => { setSettingsDraft({ ...settingsDraft, name: event.target.value }); setStatus('') }} placeholder="Örn. Alpargu" /></label><label>Günlük focus hedefi<NumberInput unit="dakika" min="15" max="1440" step="1" value={focusMinutes} onChange={(event) => { setFocusMinutes(event.target.value); setStatus('') }} /></label><label className="toggle-label"><input type="checkbox" checked={settingsDraft.compactToday} onChange={(event) => setSettingsDraft({ ...settingsDraft, compactToday: event.target.checked })} /><span><strong>Sade Bugün ekranı</strong><small>Başlangıç alanını daha kısa ve odaklı tutar.</small></span></label><fieldset className="experience-preferences"><legend>Görünüm ve geri bildirim</legend><label className="toggle-label"><input type="checkbox" checked={settingsDraft.reduceMotion ?? false} onChange={event => setSettingsDraft({ ...settingsDraft, reduceMotion: event.target.checked })} /><span><strong>Hareketi azalt</strong><small>Geçişleri ve kutlama hareketlerini kapatır. Sistem tercihin de dikkate alınır.</small></span></label><label className="toggle-label"><input type="checkbox" checked={settingsDraft.celebrationSound ?? false} onChange={event => setSettingsDraft({ ...settingsDraft, celebrationSound: event.target.checked })} /><span><strong>Başarı sesi</strong><small>Önemli eşiklerde kısa ve hafif bir ses çalar. Varsayılan olarak kapalıdır.</small></span></label></fieldset><button className="timer-button" type="submit">Profili kaydet</button><button className="data-settings-button" type="button" onClick={onOpenData}>Yedekleme, içe aktarma ve Gemini →</button></form>}
    {tab === 'focus' && <FocusCategoryManager categories={state.focusCategories} disabled={hasActiveFocus} onAdd={onAddFocusCategory} onSave={onSaveFocusCategory} onArchive={onArchiveFocusCategory} onDelete={onDeleteFocusCategory} onStatus={setStatus} />}
    {tab === 'habits' && <HabitManager habits={state.habits} onSave={onSaveHabit} onArchive={onArchiveHabit} onDelete={onDeleteHabit} onStatus={setStatus} />}
    {tab === 'reminders' && <form className="settings-form" onSubmit={saveReminders}><div className="permission-card"><div><strong>Tarayıcı bildirimleri</strong><p>{typeof Notification === 'undefined' ? 'Desteklenmiyor' : Notification.permission === 'granted' ? 'İzin verildi' : Notification.permission === 'denied' ? 'Tarayıcıda engellendi' : 'Henüz izin verilmedi'}</p></div><button type="button" onClick={requestNotificationPermission} disabled={typeof Notification !== 'undefined' && Notification.permission === 'denied'}>İzin ver</button></div><label className="toggle-label"><input type="checkbox" checked={settingsDraft.reminders.enabled} onChange={(event) => setSettingsDraft({ ...settingsDraft, reminders: { ...settingsDraft.reminders, enabled: event.target.checked } })} /><span><strong>Günlük hatırlatıcıları aç</strong><small>Plan, alışkanlık ve gün sonu bildirimleri.</small></span></label><div className="reminder-grid"><label>Sabah planı<input type="time" value={settingsDraft.reminders.planTime} onChange={(event) => setSettingsDraft({ ...settingsDraft, reminders: { ...settingsDraft.reminders, planTime: event.target.value } })} /></label><label>Alışkanlıklar<input type="time" value={settingsDraft.reminders.habitsTime} onChange={(event) => setSettingsDraft({ ...settingsDraft, reminders: { ...settingsDraft.reminders, habitsTime: event.target.value } })} /></label><label>Gün sonu<input type="time" value={settingsDraft.reminders.reflectionTime} onChange={(event) => setSettingsDraft({ ...settingsDraft, reminders: { ...settingsDraft.reminders, reflectionTime: event.target.value } })} /></label><label>Pazar özeti<input type="time" value={settingsDraft.reminders.weeklyTime} disabled={!settingsDraft.reminders.weeklyEnabled} onChange={(event) => setSettingsDraft({ ...settingsDraft, reminders: { ...settingsDraft.reminders, weeklyTime: event.target.value } })} /></label></div><label className="toggle-label"><input type="checkbox" checked={settingsDraft.reminders.weeklyEnabled} onChange={(event) => setSettingsDraft({ ...settingsDraft, reminders: { ...settingsDraft.reminders, weeklyEnabled: event.target.checked } })} /><span><strong>Pazar haftalık özetini hatırlat</strong></span></label><p className="subtle">Bilgisayarda bildirimlerin gelmesi için Momentum’un tarayıcıda veya yüklenmiş uygulama olarak açık olması gerekir.</p><button className="timer-button" type="submit">Hatırlatıcıları kaydet</button></form>}
    {status && <p className={`settings-status ${status.includes('boş') || status.includes('olmalı') || status.includes('reddedildi') || status.includes('Önce') ? 'error' : ''}`} role="status">{status}</p>}
  </AccessibleModal>
}

function FocusCategoryManager({ categories, disabled, onAdd, onSave, onArchive, onDelete, onStatus }: { categories: FocusCategory[]; disabled: boolean; onAdd: (category: Omit<FocusCategory, 'id'>) => Promise<boolean>; onSave: (category: FocusCategory) => Promise<boolean>; onArchive: (id: string, archived: boolean) => Promise<boolean>; onDelete: (id: string) => Promise<boolean>; onStatus: (message: string) => void }) {
  const [draft, setDraft] = useState({ title: '', icon: '⏱️', area: 'Kariyer' as Area })
  const activeCount = categories.filter((category) => !category.archived).length
  const add = async (event: FormEvent) => { event.preventDefault(); if (!draft.title.trim()) { onStatus('Focus kategorisi adı boş bırakılamaz.'); return }; if (!await onAdd({ ...draft, title: draft.title.trim() })) { onStatus('Kaydedilemedi. Girdiğin değerler korunuyor.'); return }; setDraft({ title: '', icon: '⏱️', area: 'Kariyer' }); onStatus('Yeni focus kategorisi eklendi.') }
  return <div className="management-panel">{disabled && <p className="management-warning">Açık focus oturumu varken kategorileri değiştiremezsin. Önce oturumu kaydet veya bitir.</p>}<div className="management-list">{categories.map((category) => <FocusCategoryRow key={category.id} category={category} disabled={disabled} canArchive={category.archived || activeCount > 1} onSave={async (next) => { const ok = await onSave(next); onStatus(ok ? 'Focus kategorisi güncellendi.' : 'Kaydedilemedi. Girdiğin değerler korunuyor.'); return ok }} onArchive={async (archived) => { if (!await onArchive(category.id, archived)) { onStatus('Kaydedilemedi. Tekrar dene.'); return }; onStatus(archived ? 'Focus kategorisi arşivlendi.' : 'Focus kategorisi yeniden etkinleştirildi.') }} onDelete={async () => { if (window.confirm(`${category.title} kategorisi silinsin mi? Geçmişi varsa arşivlenecek.`)) { onStatus(await onDelete(category.id) ? 'Kategori silindi veya geçmiş kayıtlarını korumak için arşivlendi.' : 'Kaydedilemedi. Tekrar dene.') } }} />)}</div><form className="management-add" onSubmit={add}><input aria-label="Yeni focus emoji" className="emoji-input" value={draft.icon} maxLength={8} onChange={(event) => setDraft({ ...draft, icon: event.target.value })} /><input aria-label="Yeni focus adı" value={draft.title} maxLength={60} placeholder="Yeni focus kategorisi" onChange={(event) => setDraft({ ...draft, title: event.target.value })} /><select aria-label="Yeni focus alanı" value={draft.area} onChange={(event) => setDraft({ ...draft, area: event.target.value as Area })}>{areas.map((area) => <option key={area}>{area}</option>)}</select><button type="submit" disabled={disabled}>Ekle</button></form></div>
}

function FocusCategoryRow({ category, disabled, canArchive, onSave, onArchive, onDelete }: { category: FocusCategory; disabled: boolean; canArchive: boolean; onSave: (category: FocusCategory) => Promise<boolean>; onArchive: (archived: boolean) => void; onDelete: () => void }) {
  const [draft, setDraft] = useState(category)
  useEffect(() => setDraft(category), [category])
  const valid = draft.title.trim().length > 0
  const changed = draft.title.trim() !== category.title || draft.icon.trim() !== category.icon || draft.area !== category.area
  return <div data-record={category.id} className={`management-row ${category.archived ? 'archived' : ''}`}><div className="management-fields"><input aria-label={`${category.title} emojisi`} className="emoji-input" value={draft.icon} maxLength={8} onChange={(event) => setDraft({ ...draft, icon: event.target.value })} /><input aria-label={`${category.title} adı`} value={draft.title} maxLength={60} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /><select aria-label={`${category.title} alanı`} value={draft.area} onChange={(event) => setDraft({ ...draft, area: event.target.value as Area })}>{areas.map((area) => <option key={area}>{area}</option>)}</select></div><div className="management-actions"><button type="button" disabled={disabled || !valid || !changed} onClick={() => onSave({ ...draft, title: draft.title.trim() })}>Kaydet</button><button type="button" disabled={disabled || (!category.archived && !canArchive)} onClick={() => onArchive(!category.archived)}>{category.archived ? 'Etkinleştir' : 'Arşivle'}</button><button type="button" className="delete-action" disabled={disabled} onClick={onDelete}>Sil</button></div></div>
}

function HabitManager({ habits, onSave, onArchive, onDelete, onStatus }: { habits: Habit[]; onSave: (habit: Habit) => Promise<boolean>; onArchive: (id: string, archived: boolean) => Promise<boolean>; onDelete: (id: string) => Promise<string>; onStatus: (message: string) => void }) {
  return <div className="management-panel"><p className="subtle">Arşivlenen alışkanlıklar yeni günlerde görünmez; geçmiş kayıtları ve istatistikleri korunur.</p><div className="management-list">{habits.map((habit) => <HabitManagerRow key={habit.id} habit={habit} onSave={async (next) => { const ok = await onSave(next); onStatus(ok ? 'Alışkanlık güncellendi.' : 'Kaydedilemedi. Girdiğin değerler korunuyor.'); return ok }} onArchive={async (archived) => { if (!await onArchive(habit.id, archived)) { onStatus('Kaydedilemedi. Tekrar dene.'); return }; onStatus(archived ? 'Alışkanlık arşivlendi.' : 'Alışkanlık yeniden etkinleştirildi.') }} onDelete={async () => { if (window.confirm(`${habit.name} alışkanlığı silinsin mi? Geçmişi varsa arşivlenecek.`)) onStatus(await onDelete(habit.id)) }} />)}</div></div>
}

function HabitManagerRow({ habit, onSave, onArchive, onDelete }: { habit: Habit; onSave: (habit: Habit) => Promise<boolean>; onArchive: (archived: boolean) => void; onDelete: () => void }) {
  const [draft, setDraft] = useState(habit)
  useEffect(() => setDraft(habit), [habit])
  const valid = [draft.name, draft.minimum, draft.ideal].every((value) => value.trim().length > 0)
  const changed = draft.name.trim() !== habit.name || draft.icon.trim() !== habit.icon || draft.area !== habit.area || draft.minimum.trim() !== habit.minimum || draft.ideal.trim() !== habit.ideal
  return <div data-record={habit.id} className={`management-row habit-management-row ${habit.archived ? 'archived' : ''}`}><div className="management-fields habit-management-fields"><input aria-label={`${habit.name} emojisi`} className="emoji-input" value={draft.icon} maxLength={8} onChange={(event) => setDraft({ ...draft, icon: event.target.value })} /><input aria-label={`${habit.name} adı`} value={draft.name} maxLength={60} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><select aria-label={`${habit.name} alanı`} value={draft.area} onChange={(event) => setDraft({ ...draft, area: event.target.value as Area })}>{areas.map((area) => <option key={area}>{area}</option>)}</select><input aria-label={`${habit.name} minimum hedefi`} value={draft.minimum} maxLength={40} placeholder="Minimum" onChange={(event) => setDraft({ ...draft, minimum: event.target.value })} /><input aria-label={`${habit.name} ideal hedefi`} value={draft.ideal} maxLength={40} placeholder="İdeal" onChange={(event) => setDraft({ ...draft, ideal: event.target.value })} /></div><div className="management-actions"><button type="button" disabled={!valid || !changed} onClick={() => onSave(draft)}>Kaydet</button><button type="button" onClick={() => onArchive(!habit.archived)}>{habit.archived ? 'Etkinleştir' : 'Arşivle'}</button><button type="button" className="delete-action" onClick={onDelete}>Sil</button></div></div>
}
