import { AreaIcon } from './Icon'
import { NumberInput } from './NumberInput'
import { type FormEvent, useState } from 'react'
import type { AppState, UserSettings } from '../lib/domain'
import { AccessibleModal } from './AccessibleModal'

export function OnboardingModal({ state, onComplete }: { state: AppState; onComplete: (settings: UserSettings, enabledHabitIds: string[], enabledFocusIds: string[]) => void }) {
  const [name, setName] = useState(state.settings.name)
  const [minutes, setMinutes] = useState(String(state.settings.dailyFocusMinutes))
  const [habitIds, setHabitIds] = useState(() => state.habits.filter((habit) => !habit.archived).map((habit) => habit.id))
  const [focusIds, setFocusIds] = useState(() => state.focusCategories.filter((category) => !category.archived).map((category) => category.id))
  const [error, setError] = useState('')
  const toggle = (values: string[], id: string, setter: (next: string[]) => void) => setter(values.includes(id) ? values.filter((value) => value !== id) : [...values, id])
  const submit = (event: FormEvent) => { event.preventDefault(); const target = Number(minutes); if (!name.trim()) { setError('Devam etmek için adını yaz.'); return }; if (!Number.isFinite(target) || target < 15 || target > 1440) { setError('Günlük focus hedefi 15–1440 dakika arasında olmalı.'); return }; if (!focusIds.length) { setError('En az bir focus kategorisi seç.'); return }; if (!habitIds.length) { setError('En az bir alışkanlık seç.'); return }; onComplete({ ...state.settings, name: name.trim(), dailyFocusMinutes: Math.round(target), onboardingComplete: true }, habitIds, focusIds) }
  return <div className="onboarding-backdrop"><AccessibleModal label="Momentum ilk kurulumu" className="modal-shell" dismissible={false}><form className="card onboarding-modal" onSubmit={submit}><div className="onboarding-intro"><span className="brand-mark">M</span><div><p className="eyebrow">İLK KURULUM</p><h2>Momentum’unu kendine göre kur.</h2><p>Burada seçtiklerini daha sonra ayarlardan değiştirebilirsin.</p></div></div><div className="onboarding-profile"><label>Adın<input autoFocus value={name} maxLength={60} onChange={(event) => { setName(event.target.value); setError('') }} placeholder="Sana nasıl hitap edelim?" /></label><label>Günlük focus hedefi<NumberInput unit="dakika" min="15" max="1440" step="1" value={minutes} onChange={(event) => { setMinutes(event.target.value); setError('') }} /></label></div><fieldset><legend>Focus kategorilerin</legend><div className="setup-options">{state.focusCategories.map((category) => <button type="button" className={focusIds.includes(category.id) ? 'selected' : ''} aria-pressed={focusIds.includes(category.id)} key={category.id} onClick={() => { toggle(focusIds, category.id, setFocusIds); setError('') }}><AreaIcon area={category.area} />{category.title}<small>{category.area}</small></button>)}</div></fieldset><fieldset><legend>Başlangıç alışkanlıkların</legend><div className="setup-options">{state.habits.map((habit) => <button type="button" className={habitIds.includes(habit.id) ? 'selected' : ''} aria-pressed={habitIds.includes(habit.id)} key={habit.id} onClick={() => { toggle(habitIds, habit.id, setHabitIds); setError('') }}><AreaIcon area={habit.area} />{habit.name}<small>{habit.minimum} → {habit.ideal}</small></button>)}</div></fieldset>{error && <p className="form-error onboarding-error" role="alert">{error}</p>}<button className="timer-button" type="submit">Momentum’u başlat</button></form></AccessibleModal></div>
}
