import { type FormEvent, useState } from 'react'
import type { DailyPlanItem, FocusSession } from '../lib/domain'
import { saveFailure } from '../lib/experience'
import { AccessibleModal } from './AccessibleModal'

export function DailyPlan({ plan, carryCount, draft, error, onCarry, onDraftChange, onAdd, onUpdate, onRemove }: { plan: DailyPlanItem[]; carryCount: number; draft: string; error: string; onCarry: () => void; onDraftChange: (value: string) => void; onAdd: (event: FormEvent) => void; onUpdate: (id: string, update: Partial<DailyPlanItem>) => Promise<boolean>; onRemove: (id: string) => void }) {
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editingText, setEditingText] = useState('')
  const startEditing = (item: DailyPlanItem) => { setEditingId(item.id); setEditingText(item.text) }
  const saveEdit = async (id: string) => { const text = editingText.trim(); if (text && await onUpdate(id, { text })) setEditingId(null) }
  return <article className="card plan-card"><div className="card-heading"><div><p className="eyebrow">BUGÜNÜN ÖNCELİKLERİ</p><h2>En önemli 3 iş</h2></div><span className="date-pill">{plan.length}/3</span></div>{carryCount > 0 && <button type="button" className="carry-plans" onClick={onCarry}>↪ Dünden kalan {carryCount} işi bugüne taşı</button>}<form className="plan-add" onSubmit={onAdd}><input value={draft} maxLength={100} onChange={(event) => onDraftChange(event.target.value)} placeholder="Örn. Veri Yapıları ödevini bitir" aria-label="Yeni önemli iş" /><button type="submit" disabled={plan.length >= 3}>Ekle</button></form>{error && <p className="form-error" role="alert">{error}</p>}<div className="plan-list">{plan.length === 0 && <p className="empty-state">Bugün için tek bir net iş seçerek başla.</p>}{plan.map((item) => <div className={`plan-item ${item.completed ? 'plan-complete' : ''}`} key={item.id} data-record={item.id}><button className="plan-check" aria-label={`${item.text} tamamlandı`} onClick={() => onUpdate(item.id, { completed: !item.completed })}>{item.completed ? '✓' : ''}</button>{editingId === item.id ? <input className="plan-edit-input" value={editingText} onChange={(event) => setEditingText(event.target.value)} aria-label="İşi düzenle" onKeyDown={(event) => { if (event.key === 'Enter') saveEdit(item.id); if (event.key === 'Escape') setEditingId(null) }} /> : <span>{item.text}{item.carriedFrom && <small className="carried-label">Dünden taşındı</small>}</span>}<div className="plan-item-actions">{editingId === item.id ? <><button onClick={() => saveEdit(item.id)}>Kaydet</button><button onClick={() => setEditingId(null)}>Vazgeç</button></> : <><button onClick={() => startEditing(item)}>Düzenle</button><button onClick={() => onRemove(item.id)} className="delete-action">Sil</button></>}</div></div>)}</div></article>
}

export function FocusNoteModal({ session, onClose, onSave }: { session?: FocusSession; onClose: () => void; onSave: (id: string, note: string) => Promise<boolean> }) {
  const [note, setNote] = useState(session?.note ?? '')
  const [error, setError] = useState('')
  if (!session) return null
  return <AccessibleModal label="Odak oturumu notu" className="card focus-note-modal" onClose={onClose}><div className="card-heading"><div><p className="eyebrow">OTURUM TAMAMLANDI</p><h2>{session.title}</h2></div><button type="button" className="modal-close" aria-label="Kapat" onClick={onClose}>×</button></div>{session.intention && <p className="focus-note-intention">Niyet: {session.intention}</p>}<label>Ne başardın veya sıradaki adım ne?<textarea autoFocus maxLength={1000} value={note} onChange={(event) => { setNote(event.target.value); setError('') }} placeholder="Kısa bir kapanış notu…" /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="focus-note-actions"><button type="button" className="timer-button" onClick={async () => { if (!await onSave(session.id, note)) setError(saveFailure) }}>Notu kaydet</button><button type="button" className="quiet-button" onClick={onClose}>Şimdi değil</button></div></AccessibleModal>
}
